### PR TITLE
tranlation

### PR DESCRIPTION
**Pull request by blaisefonseca**

### CODE REVIEW

**Comment by blaisefonseca** [comment]
> Can this translation server module be separated and used everywhere? So only one version is maintained?
> 
> You can consider using static classes in place of the nested functions.

this tool will facilitate translation..not sure if we need to code somewhere else

**Comment by sbilodeau** [comment]
@randyhoulahan I am under the impression that this can extended to more than juste the articles but any "translatable" collections that we have in mongo db.

**Comment by sbilodeau** [comment]
I'm not 100% sure what this do. it make calls to git

**Comment by blaisefonseca** [comment]
> @randyhoulahan I am under the impression that this can extended to more than juste the articles but any "translatable" collections that we have in mongo db.

yes thats the idea, but it needs discussion what path we need to go, for now ABS articles needs to be translated, and because Lydia will be managing it, its better online..

**Comment by blaisefonseca** [comment]
> I'm not 100% sure what this do. it make calls to git

the git query gets only files that have been modified in the selected release

**Comment by sbilodeau** [comment]
I have very big concerns about the custom api which do not implement any security. it allow all http verbs, don't have any  query-string  parameters sanitization of any kind.

**Comment by sbilodeau** [comment]
how do you track changes in the db records?

**Comment by blaisefonseca** [comment]
> I have very big concerns about the custom api which do not implement any security. it allow all http verbs, don't have any query-string parameters sanitization of any kind.

thanks, replaced with get

**Comment by blaisefonseca** [comment]
> how do you track changes in the db records?

this is the GAIA part which will need discussions, i have some ideas I will write in features

**Comment by randyhoulahan** [comment]
> @randyhoulahan I am under the impression that this can extended to more than juste the articles but any "translatable" collections that we have in mongo db.

Yes I realize my error.  I thought it was the translation logic used in the clearing houses.

**Comment by blaisefonseca** [comment]
screenshot 2019-01-29 at 1 53 01 pm

**Comment by sbilodeau** [comment]
@blaisefonseca Please go live if it prevents Lydia to work and we discuss this tomorrow

**Comment by sbilodeau** [comment]
> I have very big concerns about the custom api which do not implement any security. it allow all http verbs, don't have any query-string parameters sanitization of any kind.
>
> thanks, replaced with get

Can you quickly add add user check? call user gaia user and check roles (eg scbdstaff) as middle ware. just to avoid anonymous DOS on zipping files

**Comment by blaisefonseca** [comment]
> > I have very big concerns about the custom api which do not implement any security. it allow all http verbs, don't have any query-string parameters sanitization of any kind.
> > thanks, replaced with get
> 
> Can you quickly add add user check? call user gaia user and check roles (eg scbdstaff) as middle ware. just to avoid anonymous DOS on zipping files

i implemented authentication but i can't use it as i need to download the zip file which i have to open in new tab, can we discuss this further as we have this issue with KM too..I will go ahead with the release, lets discuss on Thursday

**Pull request merged**
